"""empty message

Revision ID: 11ee015236b8
Revises: dc12b611c1d2
Create Date: 2021-08-28 20:11:36.728866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11ee015236b8'
down_revision = 'dc12b611c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ratings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cocktail_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktail.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'cocktail_id', 'user_id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('cocktail', sa.Column('num_of_ratings', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('cocktail', sa.Column('total_rating', sa.Float(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktail', 'total_rating')
    op.drop_column('cocktail', 'num_of_ratings')
    op.drop_table('user_ratings')
    # ### end Alembic commands ###
