"""empty message

Revision ID: 257e94ff3a86
Revises: 98894600b340
Create Date: 2021-09-25 13:44:45.788887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257e94ff3a86'
down_revision = '98894600b340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
