"""empty message

Revision ID: 64756256a348
Revises: 4c5e3c42f2c6
Create Date: 2021-08-16 21:12:03.551588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64756256a348'
down_revision = '4c5e3c42f2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_unique_constraint(None, 'cocktail', ['id'])
    op.create_unique_constraint(None, 'glassware', ['id'])
    op.create_unique_constraint(None, 'ingredient', ['id'])
    op.create_unique_constraint(None, 'method', ['id'])
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'avatar')
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.drop_constraint(None, 'method', type_='unique')
    op.drop_constraint(None, 'ingredient', type_='unique')
    op.drop_constraint(None, 'glassware', type_='unique')
    op.drop_constraint(None, 'cocktail', type_='unique')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
