"""empty message

Revision ID: 98894600b340
Revises: 11ee015236b8
Create Date: 2021-08-29 18:15:57.712821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98894600b340'
down_revision = '11ee015236b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ratings', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.drop_column('user_ratings', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ratings', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_ratings', 'user_rating')
    # ### end Alembic commands ###
