"""empty message

Revision ID: b18ef9b9b92b
Revises: 64756256a348
Create Date: 2021-08-20 22:17:05.232889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b18ef9b9b92b'
down_revision = '64756256a348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=False))
    op.alter_column('user', 'id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR())
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
