"""empty message

Revision ID: dc12b611c1d2
Revises: 31ecaf49d980
Create Date: 2021-08-22 15:23:54.141457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc12b611c1d2'
down_revision = '31ecaf49d980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktail_favorites',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cocktail_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktail.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cocktail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cocktail_favorites')
    # ### end Alembic commands ###
